INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('1', 'Target C#', 'Beginners C#', '11.99', '100');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('2', 'Java Beginners', 'Introduction to Java', '12.99', '200');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('3', 'HTML', 'HTML 5', '13.99', '3');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('4', 'CSS', 'CSS 3 & Bootstrap', '14.99', '4');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('5', 'JavaScript', 'JavaScript Essentials', '15.99', '5');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('6', 'ReactJS', 'React Beginners to Advanced', '16.99', '6');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('7', 'Spring Boot', 'Spring Boot - Backend Development', '17.99', '7');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('8', 'Git', 'Version Control With Git', '18.99', '8');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('9', 'Jenkins', 'Continuous Development using Jenkins ', '19.99', '9');
INSERT INTO PRODUCTS(ID, NAME, DESCRIPTION,PRICE, STOCK) VALUES ('10','Test Driven Development', 'Test Driven Development - JUnit','20.99','10');
INSERT INTO REVIEWS(ID, NAME, DESCRIPTION, REVIEW) VALUES ('1', 'Java', 'Program Practically With Java (IntelliJ IDE Version)', 'This book is an excellent introductory text for anyone new to Java.');